### ISSUE TITLE
Request for smoke test help (MacOS, Linux, Windows)

### ISSUE THREAD

**Issue by SpecOps2016** [nus-cs2103-AY2223S1/forum#294]
I would appreicate it if someone can help me test my Duke,jar file on Linux, Windows and macOS. Thank you!

The link to my jar file can be found here: https://github.com/SpecOps2016/ip/releases/tag/A-Releases

**Comment by RussellDash332** [comment]
Tested with Windows. The two inputs below seem to be an issue to resolve.

<img src="https://user-images.githubusercontent.com/63991775/191826634-41df0f77-0887-4220-a979-5341f33cdf8e.png" width=40%>

The `find` command seems to have an issue as well.

<img src="https://user-images.githubusercontent.com/63991775/191826841-ef1a9a90-04d5-4f28-adbf-a6a84a3b1d2c.png" width=40%>

**Comment by Yongbeom-Kim** [comment]
I am on Ubuntu 20.04.5 WSL,

Note that your app suffers from https://github.com/nus-cs2103-AY2223S1/forum/issues/246:
```
dernbu@MSI:/mnt/c/Users/Dernbu/Downloads/CS2103 Testing$ java -jar  duke.jar

(java:28334): Gdk-CRITICAL **: 09:42:37.492: gdk_x11_display_set_window_scale: assertion 'GDK_IS_X11_DISPLAY (display)' failed
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f54217c9420, pid=28334, tid=28369
#
# JRE version: Java(TM) SE Runtime Environment (18.0.2.1+1) (build 18.0.2.1+1-1)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (18.0.2.1+1-1, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libX11.so.6+0x29420]  XInternAtom+0x40
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /mnt/c/Users/Dernbu/Downloads/CS2103 Testing/hs_err_pid28334.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted
```
Running with `java -Djdk.gtk.version=2 -jar duke.jar`, your app works fine
Same issue to resolve as above:
![image](https://user-images.githubusercontent.com/63487502/191878538-a1ae82ff-8c00-433d-8316-7fc3ce0754d4.png)
File IO works fine as well

**Comment by SpecOps2016** [comment]
Thank you guys! I have fixed some of the bugs. Would appreciate it if yall can run it again :)

**Comment by Yongbeom-Kim** [comment]
https://github.com/nus-cs2103-AY2223S1/forum/issues/246 is still an issue - pls bump ur javafx version to 11.0.2

Other than that, LGTM!
![image](https://user-images.githubusercontent.com/63487502/191924339-a0c31853-56a4-4725-8510-37de568c2481.png)

**Comment by SpecOps2016** [comment]
@Yongbeom-Kim I have updated my JavaFX. I would appreciate it if you can run it again. Thank you!
